### ISSUE TITLE
ALEXXX

### ISSUE THREAD

**Issue by TechDudie** [SirAlexBigBrain/UnitedWestwoodFederation#2]
sorry im sick i just added some GOD features

https://techdude.pythonanywhere.com/reviews.html

**Comment by TechDudie** [comment]
![CF67D74B-6B23-4686-B594-F9D59825D0CF](https://user-images.githubusercontent.com/73961295/167198934-10988b34-1423-4a8a-b5dc-20aa2243c0c3.png)

**Comment by TechDudie** [comment]
transitions :O

**Comment by TechDudie** [comment]
what do YOU think? tell me ALL about IT. EVERYTHING

https://techdude.pythonanywhere.com/feedback.html

**Comment by TechDudie** [comment]
YOU ID10+

**Comment by TechDudie** [comment]
2022-05-06 20:12:14,660: Exception on /reviews.html [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/TechDude/grassbandits/app.py", line 88, in reviewz
    stars = '<span>&bigstar;</span>' * int(view["stars"])
ValueError: invalid literal for int() with base 10: ''

**Comment by TechDudie** [comment]
192.150.174.6
192.150.174.18

free ips sweet

**Comment by TechDudie** [comment]
YOUUUUU

**Comment by TechDudie** [comment]
![E59E25D5-18C5-4105-8DCB-BDE084C76B3A](https://user-images.githubusercontent.com/73961295/167211913-d0aa84c3-8ff7-4a77-a153-9321b6a5b09e.png)

**Comment by TechDudie** [comment]
much better fixxed

**Comment by SirAlexBigBrain** [comment]
Ha ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha  ha ha ha

**Comment by TechDudie** [comment]
frixxed
